ARG docker_registry=p21d11107559001.azurecr.io/
FROM ${docker_registry}3rdparty/taurus:1.15.3

COPY target/tradecomm-limits-perf-tests.jar /bzt-configs/tests.jar
COPY src/test/resources/taurus/* /bzt-configs/
